/**
 * ESG Pillar Management taxonomy.
 *
 * Sector → Industry → Pillar → Topic → SubMetric → Section → Question → Response.
 *
 * Frontend leads; the eventual backend schema will mirror this shape, so the
 * types here are written to be API-ready (stable string ids, explicit ordering
 * via array position, draft/active status on questions).
 */

export type LevelKey = "sector" | "industry" | "pillar" | "topic" | "submetric";

export const PILLAR_KEYS = [
  "environmental",
  "socialCapital",
  "humanCapital",
  "businessModel",
  "leadershipGovernance",
] as const;

export type PillarKey = (typeof PILLAR_KEYS)[number];

export const PILLAR_LABELS: Record<PillarKey, string> = {
  environmental: "Environmental",
  socialCapital: "Social Capital",
  humanCapital: "Human Capital",
  businessModel: "Business Model and Innovation",
  leadershipGovernance: "Leadership and Governance",
};

/* ---------- Form-builder primitives ---------- */

export const RESPONSE_TYPES = [
  "numericInput",
  "numericalValue",
  "shortAnswer",
  "longAnswer",
  "dropdown",
  "multipleChoice",
  "checkboxes",
  "toggle",
  "date",
  "fileUpload",
] as const;

export type ResponseType = (typeof RESPONSE_TYPES)[number];

export const RESPONSE_TYPE_LABELS: Record<ResponseType, string> = {
  numericInput: "Numeric Input",
  numericalValue: "Numerical Value",
  shortAnswer: "Short Answer",
  longAnswer: "Long Answer (Paragraph)",
  dropdown: "Dropdown",
  multipleChoice: "Single Choice (Radio)",
  checkboxes: "Multi-Select (Checkboxes)",
  toggle: "Toggle (Yes / No)",
  date: "Date",
  fileUpload: "File Upload",
};

export type NumericalSubType = "integer" | "decimal" | "percent";

export interface ResponseOption {
  id: string;
  label: string;
}

export interface Response {
  id: string;
  type: ResponseType;
  /** Title shown above the input — e.g. "Volume of Fuel Consumed" */
  title: string;
  /** Helper / placeholder copy */
  helper?: string;
  /** Options for dropdown / multipleChoice / checkboxes */
  options?: ResponseOption[];
  /** Sub-type for `numericalValue` (integer/decimal/percent) */
  numericalSubType?: NumericalSubType;
}

export type QuestionStatus = "draft" | "active";

export interface Question {
  id: string;
  /** Display number, e.g. "1.1", "2.3". Generated by section index + position. */
  number: string;
  text: string;
  required: boolean;
  status: QuestionStatus;
  responses: Response[];
}

export interface Section {
  id: string;
  name: string;
  description?: string;
  questions: Question[];
}

/**
 * A Group is the dark-band header inside the sub-metric editor — corresponds
 * 1:1 with a backend `groupKey` like `environment.ghg.scope1.stationarySources`.
 * Sections inside a Group map to per-form sub-keys (e.g. electricityHeat,
 * industrialProcesses, oilGasOperations under Stationary Sources).
 */
export interface Group {
  id: string;
  name: string;
  description?: string;
  /** Backend groupKey, optional today; will be required once persistence lands. */
  groupKey?: string;
  sections: Section[];
}

/* ---------- Taxonomy ---------- */

export interface SubMetric {
  id: string;
  name: string;
  /** e.g. "DIRECT EMISSION" — uppercase tag shown next to the sub-metric name */
  category?: string;
  description?: string;
  /** Comma-joined leaf labels shown beneath the sub-metric on the topic page. Cosmetic — drives the leaves caption only. */
  leafLabels?: string[];
  /** Groups inside the sub-metric editor. Each group is a dark-band section in the UI and corresponds to a backend groupKey. */
  groups?: Group[];
}

export interface Topic {
  id: string;
  name: string;
  description: string;
  /** IFRS / SASB code shown in the topic row, e.g. "EM-EP-110a" or a range like "EM-EP-140a.1 - 140a.4". */
  ifrsCode: string;
  /** Optional form count copy shown next to the IFRS code (e.g. "4 form"). */
  formCountLabel?: string;
  subMetrics: SubMetric[];
}

export interface PillarSection {
  id: string;
  key: PillarKey;
  topics: Topic[];
}

export interface Industry {
  id: string;
  /** Short industry code shown in tree pill, e.g. "EM-OP" */
  code: string;
  /** Full SASB code, e.g. "SASB-EP" */
  sasbCode: string;
  name: string;
  description: string;
  pillars: PillarSection[];
}

export interface Sector {
  id: string;
  /** Two-letter shortcode shown in tree pill, e.g. "EM" */
  code: string;
  /** Full SASB code, e.g. "SASB-EM" */
  sasbCode: string;
  name: string;
  description: string;
  industries: Industry[];
}

/* ------- aggregate helpers (UI counts) ------- */

export function countIndustries(sector: Sector): number {
  return sector.industries.length;
}

export function countTopicsInIndustry(industry: Industry): number {
  return industry.pillars.reduce((sum, p) => sum + p.topics.length, 0);
}

export function countSubMetricsInIndustry(industry: Industry): number {
  return industry.pillars.reduce(
    (sum, p) => sum + p.topics.reduce((s, t) => s + t.subMetrics.length, 0),
    0
  );
}

export function countTopicsInSector(sector: Sector): number {
  return sector.industries.reduce((sum, i) => sum + countTopicsInIndustry(i), 0);
}

export function countSubMetricsInSector(sector: Sector): number {
  return sector.industries.reduce((sum, i) => sum + countSubMetricsInIndustry(i), 0);
}
